name: Pylint-Main

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
        pytest app.py
    - name: Build with Azure
      uses: azure/appservice-build@v1
      with:
        platform: python
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'devbook-luke'
        slot-name: 'production'
        publish-profile: ${{ secrets.azurePublishProfile}}
    
    
      
    
